const data = [
    {
      id: 'best-01',
      image: process.env.PUBLIC_URL+'/lika_img/product_1.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_1_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_1.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_2.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_3.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_4.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_5.gif',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_6.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_7.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_9.gif',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_10.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_11.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_12.gif',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_13.gif',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_14.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_15.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_16.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_17.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_18.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_19.jpg'
    ],
      desc: '199,000원',
      title: '리뉴얼 리카백 이동가방',
      price: '143,200원',
      text: '반려인과 반려동물 모두를 위한 이동가방. 1년의 준비 기간과 7번의 샘플 과정 끝에, 리카리카가 자신있게 선보이는 리카백 입니다.',
      sort: '리빙',
      option: {
        size: ['M', 'L'],
        color: ['아이보리', '베이지']
      }
    },
    {
      id: 'best-02',
      image: process.env.PUBLIC_URL+'/lika_img/product_2.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_2_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail1/detail1_1.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_006.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_008.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_010.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_014.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_015.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_017.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_018.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_019.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_020.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_021.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_022.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_023.gif',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_024.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_025.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_026.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_027.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_028.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_029.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail2/p_030.jpg'
      ],
      desc: '199,000원',
      title: '에어쉘 카시트',
      price: '149,200원',
      text: '이제 안전하게 운전하세요! 소중한 내 가족을 위한 선택이 아닌 필수',
      sort: '리빙',
      option: {
        size: ['단품'],
        color: ['베이지']
      }
    },
    {
      id: 'best-03',
      image: process.env.PUBLIC_URL+'/lika_img/product_3.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_3_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail3/p_031.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_032.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_033.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_034.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_035.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_036.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_037.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_038.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_039.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_040.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_041.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_042.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_043.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_044.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_045.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_046.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_047.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_048.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_049.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_050.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_051.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_052.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_053.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_054.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_055.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_056.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_057.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_058.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_059.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_060.gif',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_061.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_062.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_063.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_064.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail3/p_065.jpg',
    ],
      desc: '199,000원',
      title: '쿠션백 이동가방',
      price: '155,200원',
      text: '더 넓어진 공간, 더 가벼운 무게',
      sort: '리빙',
      option: {
        size: ['M','L'],
        color: ['크림','차콜']
      }
    },
    {
      id: 'best-04',
      image: process.env.PUBLIC_URL+'/lika_img/product_4.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_4_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail4/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_006.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_008.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_009.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_010.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_012.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_013.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_014.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_015.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_017.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_018.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_019.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_020.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_021.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_022.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_023.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_024.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_025.gif',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_026.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_027.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_028.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail4/p_029.jpg',
      ],
      desc: '139,000원',
      title: '튼튼 반달 슬링백 확장형',
      price: '97,300원',
      text: '18cm 확장형 메쉬망으로 업그레이드!',
      sort: '리빙',
      option: {
        size: ['M','L'],
        color: ['크림','차콜']
      }
    },
    {
      id: 'best-05',
      image: process.env.PUBLIC_URL+'/lika_img/product_5.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_5_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail5/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_005.gif',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_007.gif',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_008.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_009.gif',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_010.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_013.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_014.gif',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_015.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_017.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_018.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_019.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_020.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_021.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_022.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail5/p_023.jpg',
      ],
      desc: '58,000원',
      title: '코튼 캔디 L자형 산책용품 세트',
      price: '49,800원',
      text: '코튼 캔디 L자형 하네스와 리드줄 세트 상품입니다.',
      sort: '산책',
      option: {
        size: ['M','L'],
        color: ['아이보리','옐로우','베이비핑크','카키']
      }
    },
    {
      id: 'best-06',
      image: process.env.PUBLIC_URL+'/lika_img/product_6.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_6_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail6/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_005.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_007.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_008.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_009.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_010.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_011.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_013.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_014.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_015.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_017.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_018.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_019.gif',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_020.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_021.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_022.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_023.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_024.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_025.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_026.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_027.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_028.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail6/p_029.jpg',
      ],
      desc: '68,000원',
      title: '코튼 캔디 X자형 산책용품 세트',
      price: '59,000원',
      text: '코튼 캔디 X자형 하네스와 리드줄 세트 상품입니다.',
      sort: '산책',
      option: {
        size: ['S','M','L'],
        color: ['아이보리','옐로우','베이비핑크','카키']
      }
    },
    {
      id: 'best-07',
      image: process.env.PUBLIC_URL+'/lika_img/product_7.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_7_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail7/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_006.gif',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_008.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_010.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_013.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail7/p_014.jpg',
      ],
      desc: '35,000원',
      title: '플레이 포인트 티셔츠',
      price: '31,500원',
      text: '매일 입히고 싶은 편안함!',
      sort: '패션',
      option: {
        size: ['SM','M','L','XL','2XL'],
        color: ['머스터드','퍼플','네이비']
      }
    },
    {
      id: 'best-08',
      image: process.env.PUBLIC_URL+'/lika_img/product_8.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_8_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail8/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_008.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_010.gif',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_013.gif',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_014.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_015.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail8/p_017.jpg',
      ],
      desc: '79,000원',
      title: '포근니트',
      price: '55,300원',
      text: '오직 리카리카에서 만나볼 수 있는 자체 편직, 귀엽고 포근한 니트!',
      sort: '패션',
      option: {
        size: ['SM','M','L','XL','2XL'],
        color: ['토끼','곰돌이','코알라']
      }
    },
    {
      id: 'best-09',
      image: process.env.PUBLIC_URL+'/lika_img/product_9.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_9_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail9/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_005.gif',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_008.gif',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_010.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_011.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail9/p_013.jpg',
      ],
      desc: '69,000원',
      title: '눈사람 6온스 패딩',
      price: '48,300원',
      text: '눈처럼 가볍고, 따뜻함 가득한 눈사람 6온스 패딩',
      sort: '패션',
      option: {
        size: ['SM','M','L','XL','2XL'],
        color: ['스카이블루','그레이']
      }
    },
    {
      id: 'best-10',
      image: process.env.PUBLIC_URL+'/lika_img/product_10.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_10_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail10/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_002.gif',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_007.gif',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_008.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_010.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_011.gif',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_012.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_013.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_014.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_015.gif',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_016.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_017.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_018.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_019.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail10/p_020.jpg',
      ],
      desc: '28,000원',
      title: '진드기 때찌 슬리브리스',
      price: '23,800원',
      text: '뿌리지 말고, 바르지 말고, 쓱 입히기만 하세요!',
      sort: '패션',
      option: {
        size: ['SM','M','L','XL','2XL'],
        color: ['사자(그린)','호랑이(블루)']
      }
    },
    {
      id: 'best-11',
      image: process.env.PUBLIC_URL+'/lika_img/product_11.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_11_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail11/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_004.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_005.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_008.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail11/p_009.jpg',
      ],
      desc: '10,000원',
      title: '삼각김밥 노즈워크 장난감',
      price: '9,000원',
      text: '뿌리지 말고, 바르지 말고, 쓱 입히기만 하세요!',
      sort: '토이',
      option: {
        size: ['단품'],
        color: ['단품']
      }
    },
    {
      id: 'best-12',
      image: process.env.PUBLIC_URL+'/lika_img/product_12.jpg',
      banner: process.env.PUBLIC_URL+'/lika_img/product_12_1.jpg',
      detail: [
        process.env.PUBLIC_URL+'/lika_img/detail12/p_001.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_002.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_003.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_004.gif',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_005.gif',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_006.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_007.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_008.gif',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_009.jpg',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_010.gif',
        process.env.PUBLIC_URL+'/lika_img/detail12/p_011.gif',
      ],
      desc: '13,000원',
      title: '카페 노즈워크 장난감',
      price: '11,000원',
      text: '리카리카 카페 오픈! 버터향 가득한 갓 구운 소금빵, 달달하고 폭신한 딸기케이크, 디저트와 함께할 에스프레소 한 잔',
      sort: '토이',
      option: {
        size: ['단품'],
        color: ['소금빵','딸기케이크','에스프레소']
      }
    },
    
  ]
  export default data
